name: tests

on:
  schedule:
    - cron: "0 4 * * 0"  # At 04:00 on Sunday.
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk: [17, 21, 22]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'adopt'
          cache: maven
      - run: mvn -T1C --batch-mode verify
